
# This is a basic workflow to help you get started with Actions

name: entities:0.0

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : 
#    weekly #m h d/m m d/w 
    - cron:  '20 5 * * 1'
#    daily #m h d/m m d/w 
#    - cron:  '30 1 * * *'
   
jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: credocker/creml:2020.0
      env:
        GEONAMES_KEY: ${{ secrets.GEONAMES_KEY }}
      volumes:
        - ${{ github.workspace }}:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: main 
      - name: cd /cre/python/
        run: (cd /cre/python/)
      - name: cp mysecrets.py
        run: (cp mysecrets.orig.py mysecrets.py)
      - name: list module versions before
        run: (pip3 list)
      - name: Install spacy~=3.2.6
        run: (pip3 install spacy==3.2.6 nltk) #3.1.7
      - name: Install numpy
        run: (pip3 install numpy==1.23.5)
      - name: Install es_core_news_md
        run: (python3 -m spacy download es_core_news_md)
      - name: Install geocoder
        run: (pip3 install geocoder geopandas==0.9 pandas==2.0.3)
#      - name: Uninstall numpy
#        run: (pip3 uninstall -y numpy)
      - name: Install shapely   2.1.2
        run: (pip3 install shapely==2.0.1)

      - name: Install sentence-splitter
        run: (pip3 install sentence-splitter) 
      - name: Install spanish-nlp~=0.4.0
        run: (pip3 install --ignore-installed spanish-nlp~=0.4.0 unidecode pyspellchecker typing_extensions==4.5.0)   #unidecode pyspellchecker 
      - name: Install sympy   
        run: (pip3 install sympy==1.6.2 pandas==2.0.3 scipy==1.10.1 h5py==3.1.0 shapely==2.0.1 spacy==3.2.6)
      - name: Install numpy
        run: (pip3 install numpy==1.23.5)
      - name: list module versions after
        run: (pip3 list)
      - name: Run entities
        run: (python3 entities.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'csv/sentiments_*.csv'
          tag_push: '--force'
